title: Taylor O'Brien Portfolio
description: This is the portfolio website for Taylor O'Brien in the Earth Data Analytics Bootcamp course.
logo: Headshot.jpg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
