title: Taylor O'Brien Portfolio
description: This is the portfolio website for Taylor O'Brien in the Earth Data Analytics Bootcamp course.
logo: https://avatars.githubusercontent.com/u/143227722
![Headshot](https://avatars.githubusercontent.com/u/143227722)
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

